#! /usr/bin/bash

# find file extension for a file
#  echo "thisfile.txt"|awk -F . '{print $NF}'

# Holds the selected bookmark
selectedBookmark=""

# holds the path to the bookmark file
bookmarkPath="$HOME/.config/fzf-bookmarks/bookmarks"
# Path to the program config used to launch files
fileLauncherPath="$HOME/.config/fzf-bookmarks/config"

# check if fzf is installed
if   ! type "fzf" > /dev/null; then
		echo "fzf is not installed! Please install it before using this program"
		exit 1
fi

# check if the bookmark file exists
# if it does not, it will be created in the .config folder
function checkBookmarkDirectory(){
	if [ ! -d "$HOME/.config/fzf-bookmarks" ]
	then
			cd "$HOME/.config"
			mkdir "fzf-bookmarks"
			cd "fzf-bookmarks"
			touch "bookmarks"
			touch "config"
	fi
}

# Change directories to the selected bookmark
function switchToBookmark(){
	# Variable holds the number of lines in a file
	local bmarkLineNum=$(wc -l $bookmarkPath | awk '{print $1}')
	if [ $bmarkLineNum == 0 ]
	then
		printf "You do not have any bookmarks set\n"
		exit 0
	fi

	# Case of a only directories
	if [ $1 -eq 1 ]
	then
	 	selectedBookmark=$(awk ' $2 == "DIR" {print $1}' $bookmarkPath | fzf)
	 	echo $selectedBookmark
	 	if [ ! -z $selectedBookmark ]
		then 
	 		cd $(awk -v var="$selectedBookmark" '$1 == var {print $3}' $bookmarkPath)
			# make the change of directory affect the parent shell 
			# and not just the subshell
			exec bash
		 fi
	# Case of listing only files
	elif [ $1 -eq 2 ]
	then
			selectedBookmark=$(awk ' $2 == "FILE" {print $1}' $bookmarkPath | fzf)
			# Retrieve the file type
			local fileType=$(awk -v var=$selectedBookmark '$1 == var {print $4}' $bookmarkPath)
			local fileLocation=$(awk -v var=$selectedBookmark '$1 == var {print $3}' $bookmarkPath)
			# Retrieve the corresponding program used to launch
			local program=$(awk -v var=$fileType '$1 == var {print $2}' $fileLauncherPath)
			# Launch the program in a detached state
			if [ ! -z $program ]
			then
				exec "$program" "$fileLocation" "&"
			else
				printf "This filetype and its associated program is not defined in the config file!\n"
			fi

	# Case of displaying all bookmarks
	else 
		selectedBookmark=$(awk ' {print $1 $2}' $bookmarkPath | fzf)
		# Get the actual bookmark name
		selectedBookmark=$($selectedBookmark | awk '{print $1}')
	fi
}

# Add a new bookmark
# If a path is not provided then the current directory is used
function addBookmark(){
	# check if a bookmark with the name provided already exists
	local boolUnique=$(awk -v var="$1" '$1 == var {print 1}' $bookmarkPath)
	if [ "$boolUnique" == "1" ]
	then
		printf "A bookmark with that name already exists! Please enter a different one.\n"
		exit 1
	fi

	if [ -z "$2" ] 
	then
		printf "$1\tDIR\t$PWD\n" >> $bookmarkPath
	# Case of a path being provided
	elif [ -d $2 ]
	then
		printf "$1\tDIR\t$2\n" >> $bookmarkPath
		printf "Bookmark added successfully!\n"
	elif [ -e $2 ]
	then
		# retrieve the file extension
		# props to: https://liquidat.wordpress.com/2007/09/29/short-tip-get-file-extension-in-shell-script/
		local extension=$( echo "$2" | awk -F . '{print $NF}')
		printf "$1\tFILE\t$2\t$extension\n" >> $bookmarkPath
		printf "Bookmark added successfully!\n"
	else
		printf "The path provided is neither a folder or a file! It most likely does not exist!\n"
	fi
}

# Erase the entire bookmark file and create a fresh one
function eraseAllBookmarks(){
	rm $bookmarkPath
	touch $bookmarkPath
}

# Display all aliases to the user and let them select one
function selectAlias(){
	local selectedAlias=$(awk '/^alias / {print $0}' "$HOME/.bashrc" | fzf)
}

function selectManPage(){
	# hold the name of selected page 
	local selectedPage=""

	# Print all manpage sections
	if [ -z $1 ]
	then
		# variable to hold the selected manpage
		selectedPage=$(man -k . | awk '{print $1 $2}' | fzf)
		exec man $selectedPage

	# Exec manpages for selected section
	else
		selectedPage=$(apropos -s "$1" . | awk '{print $1}'| fzf)
		exec man $selectedPage
	fi
}
# Remove the specified bookmark from the bookmarks file
function removeBookmark(){
	if [ ! -z "$2" ]
	then
		printf "Too many arguments. Either provide the name of a bookmark or do not provide anything to delete through fzf\n"
	# case of no arg provided, use fzf to select
	elif [ -z "$1" ]
	then
			selectedBookmark=$(awk '{print $1}' $bookmarkPath | fzf)
			# Handle the case of the user pressing CTRL+C
			# if we do not check that $selectedBookmark is not empty
			# then the entire list of bookmarks is deleted
			if [ ! -z $selectedBookmark ]
			then
				# remove the selected bookmark
				# using sed instead of awk since we do not 
				# have to copy the entire file over
				sed -i "/^$selectedBookmark/d" $bookmarkPath
			fi
			exit 0
	# case of providing a name manually
	else 
		local selectedBookmarkIndex=$(awk -v var="$1" '$1 == var {print NR}' $bookmarkPath)
		if [ ! -z $selectedBookmarkIndex ]
		then
				# delete the line number 
				sed -i "$selectedBookmarkIndex"d "$bookmarkPath"
		else
				printf "Bookmark not found!\n"
		fi
	fi
}

checkBookmarkDirectory
# Parse script arguments
if [ -z $1 ]
then 
	# Display all bookmarks
	switchToBookmark
elif [ $1 == "-d" ]
then
	# Display directories only
	switchToBookmark 1
elif [ $1 == "-f" ]
then
	# Display Files only
	switchToBookmark 2
elif [ $1 == "-a" ]
then
	addBookmark "$2" "$3"
elif [ $1 == "-r" ]
then
	removeBookmark "$2" "$3"	
elif [ $1 == "-eraseall" ]
then
	eraseAllBookmarks
elif [ $1 == "-al" ]
then
	selectAlias	
elif [ $1 == "-m" ]
then
	selectManPage $2
fi
